import { StyleSheet } from 'react-native'

export const schedule_style_sheet = StyleSheet.create({
    schedule_item_style: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop:10,
        marginLeft:20,
    },
    schedule_title_style:{
        fontSize:19,
        fontWeight:'600',    
    },
    date_time_style:{
        width: 100,
        alignItems:'center',
        justifyContent: 'center',
        flexDirection: 'column',
        backgroundColor: '#800020',
    },
    course_container:{
        width:60,
        height:30,
        borderRadius:15,
        borderWidth:2,
        justifyContent:'center',
        alignItems:'center',
        marginRight:'2%',
        marginTop:'10%',
        backgroundColor:'#800020',
        borderColor:'#800020',
    },
    course_text:{
        color:'white',
    },
    main_container:{
        marginTop:'2%',
        marginBottom:'2%',
        marginLeft:'2%',
        marginRight:'2%',
        width:'95%',
        height:110,
        borderRadius:20,
        borderWidth:2,
        borderColor:'#800020',
        alignItems:'center',
    },
    date_container:{
        marginTop:'3%',
        marginBottom:'1%',
        marginLeft:'2%',
    },
    date_text:{
        fontSize: 20,
        color:'#800020',
        fontWeight:'600',
    },
    class_text:{
        fontSize: 20,
        color:'#800020',
        fontWeight:'600',
    },
    book_button:{
        backgroundColor:'#800020',
        borderRadius:20,
        height:40,
        width:'20%',
        marginTop:'3%',
        alignItems:'center',
        justifyContent:'center',
    },
    trainer_container:{
        flexDirection:'row',
        flexWrap:'wrap',
        marginTop:'4%',
        marginLeft:'4%',
        alignItems:'center',
        justifyContent:'center',
    },
    time_container:{
        marginTop:'2%',
        marginBottom:'2%',
        marginLeft:'2%',
        marginRight:'2%',
        width:'96%',
        height:150,
        borderRadius:20,
        borderWidth:4,
        borderColor:'#800020',
    },
    time_text_container:{
        marginTop:'5%',
        marginLeft:'5%',
    },
    time_text:{
        fontSize:20,
        fontWeight:'600',
        color:'#800020',
    },
});

